---

- name: check if created by xaas portal
  shell: grep  "CBTS XaaS Portal" /etc/snmp/snmpd.conf
  ignore_errors: yes
  changed_when: false
  register: checkforxaas
  tags: [ 'snmp' ]

#- debug: 
#    var: checkforxaas

- name: config | copying snmpd config
  template:
    src: "snmpd.conf.j2"
    dest: "/etc/snmp/snmpd.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart snmpd"
  when: checkforxaas.changed != false
  tags: [ 'snmp' ]
