---
# tasks file for selinux

- name: Install libselinux-python bindings
  yum: name=libselinux-python state=present
  tags: [ 'selinux' ]

- name: Configure selinux
  selinux: 
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  tags: [ 'selinux' ]
