---
# tasks file for ops_menu

- name: Check if already created
  stat: path=/opt/cbts/msops/scripts/ops.menu.sh
  register: installed
  tags: [ 'ops' ]

- name: Create /opt/cbts/msops/bin directory
  file:
    path: /opt/cbts/msops/bin
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
  ignore_errors: true
  when: not installed.stat.exists
  tags: [ 'ops' ]

- name: Create /opt/cbts/msops/scripts directory
  file:
    path: /opt/cbts/msops/scripts
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
  ignore_errors: true
  when: not installed.stat.exists
  tags: [ 'ops' ]

- name: Install RHEL6 OPs Menu
  copy:
    src: rhel6.ops.menu.sh
    dest: /opt/cbts/msops/scripts/ops.menu.sh
    owner: root
    group: root
    mode: 0755
  ignore_errors: true
  when:
    - ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6'
    - not installed.stat.exists
  tags: [ 'ops' ]


- name: Install RHEL7 OPs Menu
  copy:
    src: rhel7.ops.menu.sh
    dest: /opt/cbts/msops/scripts/ops.menu.sh
    owner: root
    group: root
    mode: 0755
  ignore_errors: true
  when:
    - ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
    - not installed.stat.exists
  tags: [ 'ops' ]
