---
# tasks file for install_packages
     - name: Install required packages
       yum:
         name: "{{ item }}"
         state: installed
       with_items:
         - bind-utils
         - java-1.7.0-openjdk
         - libselinux-python # Required for selinux management by Ansible
         - lshw
         - lsscsi
         - nc
         - net-snmp
         - net-snmp-utils
         - rsyslog
         - rsyslog-gnutls
         - nmap
         - ntp
         - ntpdate
         - sg3_utils
         - sysfsutils
         - wget
         - yum-utils
         - sos
         - device-mapper-multipath
         - dos2unix
         - dracut-fips
         - dstat
         - logwatch
         - net-tools
         - scrub
         - sysstat
         - vim-enhanced
         - vlock
         - xterm
         - tcpdump
         - telnet
         - tree
         - python-passlib
       when: ansible_distribution == 'RedHat'
       tags: [ 'install' ]

     - name: Copy cfg2html rpm to target
       copy:
         src: files/cfg2html-6.30-1.git201607081048.noarch.rpm
         dest: /var/tmp/cfg2html-6.30-1.git201607081048.noarch.rpm
       when: ansible_distribution == 'RedHat'
       tags: [ 'install' ]

     - name: Install cfg2html from RPM
       yum:
         name: /var/tmp/cfg2html-6.30-1.git201607081048.noarch.rpm
         state: present
       when: ansible_distribution == 'RedHat'
       tags: [ 'install' ]

