---
# tasks file for CBTS_accounts
# adds pre-defined MS-compute and CPE resources to the host being on-boarded

# Pre-reqs
#create files/<username>.pub with ssh public key
#create files/mscompute_users.yml with list of users to add.

- include_vars: files/mscompute_users.yml
  tags: [ 'adduser' ]
- include_vars: files/password_hash
  tags: [ 'adduser' ]

- name: Manage user account
  user: 
    name: "{{ item.username }}" 
    comment: "{{ item.comment }}" 
    state: "{{ item.state }}" 
    password: "{{ password }}" 
  register: user_created
  with_items: '{{ users }}'
  tags: [ 'adduser' ]

- name: Setup | authorized key upload
  authorized_key: user={{ item.username }} key={{ lookup('file', 'files/{{ item.username }}.pub') }}
  when: user_created and item.state == "present"
  with_items: '{{ users }}'
  tags: [ 'adduser' ]

- name: add user to sudoers
  lineinfile: 
     dest: /etc/sudoers.d/{{ item.username }}
     line: "{{ item.username }}       ALL = (ALL)     NOPASSWD: ALL"
     state: present
     create: yes
     validate: 'visudo -cf %s'
  with_items: '{{ users }}' 
  tags: [ 'adduser' ]

- name: Copy user bashrc to account
  copy: 
    src: files/user_bashrc
    dest: /home/{{ item.username }}/.bashrc
    owner: "{{ item.username }}"
    group: "{{ item.username }}" 
    mode: 0644
  with_items: '{{ users }}' 
  tags: [ 'adduser' ]
