--- 
# ansible-playbook password.yml -l test-servers --extra-vars "name=test1"
#

- hosts: all 
  become: yes 

  gather_facts: no 
  vars:
   username: "{{ name }}" 

  vars_prompt: 
   - name: "new_password" 
     prompt: "Enter New Password" 
     private: yes 
     encrypt: "md5_crypt" 
     confirm: yes 
     salt_size: 7 
     tags:
      - chgpasswd       

  tasks: 
#   - include_vars: files/password_hash

   - name: GetUserInfo
     shell: egrep "^{{ item }}:" /etc/passwd
     ignore_errors: yes
     with_items:
      - "{{ username }}"
     register: user_info
     tags:
      - chgpasswd       
 
   - name: Change password of existing user 
     user: 
      name: "{{ username }}"
      update_password: "always" 
      password: "{{new_password}}" 
#      password: "{{password}}" 
#     when: item.rc == 0
     with_items: "{{ user_info.results }}"
     tags:
      - chgpasswd       
