---
- hosts: all 
  become: yes 

  tasks:
    - name: Send restart command
      command: /sbin/shutdown -r now "Ansible rebooting server"
      become: yes
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for the server to restart
      become: no
#      local_action: wait_for host={{ ansible_ssh_host }} delay=30 timeout=360 state=started
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 delay=30 timeout=360 state=started

